### ISSUE TITLE
Suggestion: Host this using GitHub Pages.

### ISSUE THREAD

**Issue by NS007-dev** [isha614/Sticky-Notes#1]
@isha614 , as a suggestion, you could host your websites and apps on github pages. If you were to, you could just take out the html, css and js files, and don't put them in a folder. 

Then, change all the file names and imports to index.html, index.css, index.js.

 After, go to settings, go to the pages section, and select the main branch, and root and save:
![image](https://user-images.githubusercontent.com/70807500/130980247-7e435c74-4b95-45f2-b5c6-e5399e894f34.png)

After you save, just click the url that will show up, something like this: `isha614.github.io/Sticky-Notes/`.

In the about section, just paste your url in, and it should work. Thanks

**Comment by isha614** [comment]
Thankyou for your Suggestion! I will definitely look into it.
